name: Build NDK Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: وەرگرتنی کۆدەکان
      uses: actions/checkout@v4

    - name: بیڵدکردن بە ndk-build
      run: |
        cd 8BPGlass/8BPGlass
        $ANDROID_NDK_LATEST_HOME/ndk-build

    - name: ئامادەکردنی پەڕگەکان بۆ داگرتن
      uses: actions/upload-artifact@v4
      with:
        name: Native-Libraries
        path: 8BPGlass/8BPGlass/libs/
